### ISSUE TITLE
spree payu

### ISSUE THREAD

**Issue by YSTomar** [netguru/spree_payu_integration#10]
1 error prohibited this record from being saved:
There were problems with the following fields:

PayU error Invalid HTTP response code (400). Response body: {"resId":null,"status":{"statusCode":"ERROR_INCONSISTENT_CURRENCIES","severity":null,"code":null,"codeLiteral":null,"location":null,"statusDesc":"Order and pos currencies are

**Comment by sunny2601** [comment]
1 error prohibited this record from being saved:
There were problems with the following fields:

PayU error Invalid HTTP response code (400). Response body: {"resId":null,"status":{"statusCode":"ERROR_INCONSISTENT_CURRENCIES","severity":null,"code":null,"codeLiteral":null,"location":null,"statusDesc":"Order and pos currencies are inconsistent"},"properties":null,"redirectUri":null,"version":"2.0","orderId":null,"extOrderId":null,"payMethods":null,"redirectMobileUri":null}.

**Comment by felorodri** [comment]
Hey guys, I am getting this same issue, did you solve it?

**Comment by jigarbhatt** [comment]
Hey guys, I am getting this same issue, did you solve it?

**Comment by naliwajek** [comment]
PayU handles only PLN currency for now (even though their documentation suggests otherwise).
