### ISSUE TITLE
Getting 400 while Integrating

### ISSUE THREAD

**Issue by rajbharath** [netguru/spree_payu_integration#11]
Issue:
when I try to check out the cart, I select PayU radio button and click save and continue. I get the below response. Kindly let me know if I miss any configuration or any other stuff. I dint edit anything in openpayu.rb.

Response:
==========
PayU error Invalid HTTP response code (400). Response body: {"resId":null,"status":{"statusCode":"ERROR_INCONSISTENT_CURRENCIES","severity":null,"code":null,"codeLiteral":null,"location":null,"statusDesc":"Order and pos currencies are inconsistent"},"properties":null,"redirectUri":null,"version":"2.0","orderId":null,"extOrderId":null,"payMethods":null,"redirectMobileUri":null}.
![image](https://cloud.githubusercontent.com/assets/1915417/6583248/cfeb3970-c788-11e4-8220-b6ffbdfe7b3d.png)

Update:
Updated with the error screenshot

**Comment by naliwajek** [comment]
What currency is assigned to this order in Spree? (for example: "USD", "GBP", "EUR" etc.)

Then, please check if you've activated support for this currency in the PayU account settings.

Thanks.

**Comment by rajbharath** [comment]
Hi Naliwajek,
Thanks for the reply.

I have changed the currency to INR both in admin-> configuration-> currency and in admin -> products(for only one product for purpose of testing) -> currency. Same issue is still persists, when I try to check out  the edited product.

**Comment by rajbharath** [comment]
any update on this?

**Comment by singhraj-india** [comment]
I am also getting the same issue. Has anybody found any solution.

**Comment by denislutz** [comment]
Hi I want to start the integration with PayU is this issue solved in the meanwhile?

Thanks a lot,

....

**Comment by abhaynahar** [comment]
Hey, any updates on the issue?

**Comment by felorodri** [comment]
Looking for a solution. Does anybody found how to fix this?

**Comment by marcindobry** [comment]
We are looking into it

**Comment by ChrisEstanol** [comment]
I am also getting the same error. Any way to overcome this issue?

**Comment by denislutz** [comment]
Hey Guys, any progress on that? We would love to integrate payu. 
I usually say we finally need feature on github, to pay for missing features on frameworks as a group. I would do that here.

**Comment by Mossie93** [comment]
Currently payu handles payments only in PLN. In their REST API documentation you can find information that every currency compliant with ISO4217 standard is valid, because payu plans to enhance their services in the future.

**Comment by jigarbhatt** [comment]
Hey i m facing the same issue with dollar currency.

Is there anyone have solution for this?

**Comment by prashanthiremath** [comment]
I tried using INR currency then it gives failure of ERROR_INCONSISTENT_CURRENCIES so then I changed it to PLN currency then it gives success response. So it supports only PLN now.
