### ISSUE TITLE
spree_core version error when running 'bundle install'

### ISSUE THREAD

**Issue by rohitnick** [netguru/spree_payu_integration#13]
Getting the following error when running 'bundle install'. I am using the following in my gemfile.

**Gemfile**

    gem 'spree_payu_integration', github: 'netguru/spree_payu_integration'
    gem 'spree', '3.0.1'
    gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
    gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'

**Error**

    Bundler could not find compatible versions for gem "spree_core":
     In snapshot (Gemfile.lock):
       spree_core (= 3.0.1)

    In Gemfile:
     spree_payu_integration (>= 0) ruby depends on
       spree_core (~> 2.1.6) ruby

    Running `bundle update` will rebuild your snapshot from scratch, using only
    the gems in your Gemfile, which may resolve the conflict.

Even after running bundle update, it is showing the same error.

**Comment by naliwajek** [comment]
Changes for Spree 3.0 are now in `3-0-stable` branch.
